---
# tasks file for ansible-role-traefik

- name: Install required system packages
  apt:
    name:
      - python3-pip
    state: latest
    update_cache: yes
    cache_valid_time: "600"    
  tags:
    - install
    - packages

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Create a network
  docker_network:
    name: proxy

- include: traefik.config.dirs.yml
  tags:
    - dirs

- include: traefik.config.files.yml
  tags:
    - config_files

