---
- name: Converge
  hosts: 
    - ubuntu2004
    - debian10
  roles:
    - role: iquzart.docker 

  pre_tasks:
    - name: docker restart
      systemd:
        name: docker
        state: restarted
        enabled: true

  tasks:
    - name: "Include ansible-role-traefik"
      include_role:
        name: "ansible-role-traefik"